
# List of administration profiles. Each profile should be with
# unique password, and allows to configure access to specified
# root drives, shares, and to hide files on specified masks.

- id: 1
  login: admin
  password: dag qus fly in the sky
  roots:
  hidden:
    - ?:/system volume information
    - '*.sys'
    - '*.tmp'
    - '*.bak'
    - '*/.*'
    - ?:/windows
    - ?:/windowsapps
    - ?:/$recycle.bin
    - ?:/program files
    - ?:/program files (x86)
    - ?:/programdata
    - ?:/recovery
    - ?:/config.msi
    - '*/thumbs.db'
  shares:
    - '[home/Home]'
