
# List of administration profiles. Each profile should be with
# unique password, and allows to configure access to specified
# root paths, shares, and to hide files on specified masks.

- id: 1
  login: admin
  password: dag qus fly in the sky
  local:
  remote:
  shares:
    - path: '<home>'
      name: Home
  hidden:
    - '**/*.sys'
    - '**/*.tmp'
    - '**/*.bak'
    - '**/.*'
    - '**/Thumbs.db'
    - ?:/System Volume Information
    - ?:/Windows
    - ?:/WindowsApps
    - ?:/$Recycle.Bin
    - ?:/Program Files
    - ?:/Program Files (x86)
    - ?:/ProgramData
    - ?:/Recovery
    - ?:/Config.Msi
