
# Hidden extensions, files, directories. File names
# and directories can be patterns with '?', '*' masks.
# Patterns are case insensitive.

extensions:
    - .sys
    - .tmp
    - .bak
filenames:
    - thumbs.db
    - .*
filepaths:
    - ?:/system volume information
    - ?:/windows
    - ?:/windowsapps
    - ?:/winreagent
    - ?:/$windows.~ws
    - ?:/$recycle.bin
    - ?:/program files
    - ?:/program files (x86)
    - ?:/programdata
    - ?:/recovery
    - ?:/config.msi
---

# List of administration profiles. Each profile should be with
# unique password, and allows to configure access to specified
# root paths, shares, and to hide files on specified masks.

- id: 1
  login: admin
  password: dag qus fly in the sky
  local:
  remote:
  shares:
    - path: '<home>'
      name: Home
